# Generated by Django 5.2.3 on 2025-09-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título principal que se mostrará en el banner', max_length=200, verbose_name='Título del Banner')),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo opcional para el banner', max_length=300, verbose_name='Subtítulo')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del banner', verbose_name='Descripción')),
                ('image_filename', models.CharField(help_text='Nombre del archivo de imagen en static/images/banners/ (ej: banner1.jpg)', max_length=255, unique=True, verbose_name='Nombre del Archivo de Imagen')),
                ('is_active', models.BooleanField(default=True, help_text='Si está marcado, el banner se mostrará en la página principal', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número = mayor prioridad)', verbose_name='Orden')),
                ('button_text', models.CharField(blank=True, help_text='Texto que aparecerá en el botón de acción', max_length=50, verbose_name='Texto del Botón')),
                ('button_url', models.URLField(blank=True, help_text='URL a la que redirigirá el botón (opcional)', verbose_name='URL del Botón')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
