# Generated by Django 5.2.3 on 2025-09-11 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Facebook, Instagram, Twitter, etc.', max_length=50, verbose_name='Nombre de la Red Social')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('other', 'Otro')], default='other', help_text='Selecciona la plataforma de redes sociales', max_length=20, verbose_name='Plataforma')),
                ('url', models.URLField(help_text='URL completa del perfil o página (ej: https://www.facebook.com/tu-pagina)', validators=[django.core.validators.URLValidator()], verbose_name='URL del Perfil')),
                ('icon_class', models.CharField(default='fas fa-link', help_text='Clase CSS del icono (ej: fab fa-facebook-f)', max_length=50, verbose_name='Clase del Icono')),
                ('is_active', models.BooleanField(default=True, help_text='Si está marcado, se mostrará en el sitio web', verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número = mayor prioridad)', verbose_name='Orden')),
                ('followers_count', models.PositiveIntegerField(blank=True, help_text='Número aproximado de seguidores (opcional)', null=True, verbose_name='Número de Seguidores')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['order', 'platform'],
                'unique_together': {('platform', 'url')},
            },
        ),
    ]
