# Generated by Django 5.2.3 on 2025-09-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the image', max_length=200)),
                ('image', models.ImageField(help_text='Upload an image file (JPG, PNG, GIF). Max 5MB.', upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
            ],
            options={
                'verbose_name': 'Image Upload',
                'verbose_name_plural': 'Image Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Formatos permitidos: JPG, PNG, GIF. Tamaño máximo recomendado: 2MB', null=True, upload_to='products/'),
        ),
    ]
